### ISSUE TITLE
add summary in posts

### ISSUE THREAD

**Issue by mazulo** [dunderlabs/dunderlabs.github.io#8]

**Comment by nltncsr** [comment]
Looking at [doc](http://docs.getpelican.com/en/3.6.3/content.html?highlight=summary_max_length) I can see that there's two of ways of definig the post summary: including the metatag `summary` in each post or letting Pelican define the summary when setting a variable in pelicanconf.py of word length for the summary.
I see that there's some articles that have these tags and some that don't.

**Comment by mazulo** [comment]
Yeah, I know. This `summary` is also used to show a resume in the home (listing all posts) and the description in metatags (facebook, google+ and twitter). I'm finishing this right now.

**Comment by nltncsr** [comment]
Ok!
